---
upload_path: "/hugo/static/uploads/:year:/:month:"
frontmatter_file_url_template: "/uploads/:year:/:month:"
body_file_url_template: "/uploads/:year:/:month:"
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections: 
version: 0.31.1
